/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ts3_musicbot

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        //val classUnderTest = Main()
        //assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
